// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/model/repository.go

// Package mock_model is a generated GoMock package.
package mock_model

import (
	reflect "reflect"
	model "todo-list/internal/model"

	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AddTask mocks base method.
func (m *MockRepository) AddTask(task *model.Task, userId int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTask", task, userId)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTask indicates an expected call of AddTask.
func (mr *MockRepositoryMockRecorder) AddTask(task, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTask", reflect.TypeOf((*MockRepository)(nil).AddTask), task, userId)
}

// ChangeStatus mocks base method.
func (m *MockRepository) ChangeStatus(id string, status model.Status, userId int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeStatus", id, status, userId)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangeStatus indicates an expected call of ChangeStatus.
func (mr *MockRepositoryMockRecorder) ChangeStatus(id, status, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeStatus", reflect.TypeOf((*MockRepository)(nil).ChangeStatus), id, status, userId)
}

// DeleteTask mocks base method.
func (m *MockRepository) DeleteTask(id string, userId int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTask", id, userId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTask indicates an expected call of DeleteTask.
func (mr *MockRepositoryMockRecorder) DeleteTask(id, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTask", reflect.TypeOf((*MockRepository)(nil).DeleteTask), id, userId)
}

// EditTask mocks base method.
func (m *MockRepository) EditTask(task *model.Task, userId int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditTask", task, userId)
	ret0, _ := ret[0].(error)
	return ret0
}

// EditTask indicates an expected call of EditTask.
func (mr *MockRepositoryMockRecorder) EditTask(task, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditTask", reflect.TypeOf((*MockRepository)(nil).EditTask), task, userId)
}

// GetAllTasks mocks base method.
func (m *MockRepository) GetAllTasks(userId int32) ([]*model.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllTasks", userId)
	ret0, _ := ret[0].([]*model.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllTasks indicates an expected call of GetAllTasks.
func (mr *MockRepositoryMockRecorder) GetAllTasks(userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllTasks", reflect.TypeOf((*MockRepository)(nil).GetAllTasks), userId)
}

// GetTaskById mocks base method.
func (m *MockRepository) GetTaskById(id string, userId int32) (*model.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskById", id, userId)
	ret0, _ := ret[0].(*model.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskById indicates an expected call of GetTaskById.
func (mr *MockRepositoryMockRecorder) GetTaskById(id, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskById", reflect.TypeOf((*MockRepository)(nil).GetTaskById), id, userId)
}

// GetTasks mocks base method.
func (m *MockRepository) GetTasks(filter *model.Filter, userId int32) ([]*model.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTasks", filter, userId)
	ret0, _ := ret[0].([]*model.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTasks indicates an expected call of GetTasks.
func (mr *MockRepositoryMockRecorder) GetTasks(filter, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTasks", reflect.TypeOf((*MockRepository)(nil).GetTasks), filter, userId)
}

// GetUserByName mocks base method.
func (m *MockRepository) GetUserByName(username string) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByName", username)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByName indicates an expected call of GetUserByName.
func (mr *MockRepositoryMockRecorder) GetUserByName(username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByName", reflect.TypeOf((*MockRepository)(nil).GetUserByName), username)
}
